var languageName=['CN','US'];
var langText={
	'US':{
		'title':'Recognized Quotation',
		'field1':'Inquiry No',
		'field2':'Logistics Project No',
		'field3':'Reply Time',
		'field9':'Replier',
		'field10':'Telephone',
		'field11':'Logistics Project',
		'field12':'POL',
		'field13':'POD',
		'field14':'Carrier',
		'field4':'Port of Transshipment',
		'field5':'Journey Time',
		'field6':'Sailing Date',
		'field7':'Closing Date',
		'field8':'Valid',
		'field15':'Freight',
		'field16':'Charges',
		'field17':'Booking Fee',
		'field18':'Cost',
		'field19':'Quote',
		'field20':'Profit',
		'field21':'Confirm',
		'field22':'Sail Information',
		'field23':'(unit：dollar)',
		'field24':'profit',
		'Have_booking':'Have_booking',
		'ticket':'ticket',
		'byorder':'Byorderr',
		'currency':'Currency',
		'BatchAdd':'BatchAdd',
		'feess':'Please enter the modify cost',
	},
	'CN':{
		'title':'已确认报价',
		'field1':'询价编号',
		'field2':'物流方案编号',
		'field3':'回复时间',
		'field9':'回复人',
		'field10':'电话',
		'field11':'物流方案',
		'field12':'起运港',
		'field13':'目的港',
		'field14':'船公司',
		'field4':'中转港',
		'field5':'船程',
		'field6':'开船',
		'field7':'截关',
		'field8':'有效期',
		'field15':'运费',
		'field16':'附加费',
		'field17':'订舱费',
		'field18':'成本',
		'field19':'报价',
		'field20':'利润',
		'field21':'确认报价',
		'field22':'船期信息',
		'field23':'(单位：美元)',
		'field24':'利润',
		'Have_booking':'已订舱',
		'ticket':'票',
		'byorder':'单票',
		'currency':'币种',
		'BatchAdd':'批量添加',
		'feess':'请输入修改费用',
	}
}
//币种
var arrHyfCurrency=['(单位：人民币)','(单位：美元)','(单位：泰铢)'];
var arrCurrency=['￥','$','฿'];