var languageName=['CN','US'];
var langText={
	'US':{
		'title':'Order Details',
		'personnel':'Personnel',
		'operator':'Operator',
		'seller':'Seller',
		'Box':'Box box quantity',
		'freight':'Freight',
		'Charges':'Charges',
		'information':'Bill information',
		'Other':'Other information',
		'transport':'Mode of transport',
		'field1':'POL',
		'field2':'POD',
		'field3':'Carrier',
		'field4':'Port of Transshipment',
		'field5':'Journey Time',
		'field6':'Sailing Date',
		'field7':'Closing Date',
		'field8':'Valid Date',
		'field9':'Type&Number',
		'field10':'ETD',
		'field11':'Select Time',
		'field12':'Remark',
		'field13':'Inquiry',
		'field14':'The Ship Information',
		'field21':'See the logistics state',
		'field18':'Cost',
		'field19':'Quote',
		'field20':'Profit',
		'cost':'Cost',
		'offer':'Offer',
	},
	'CN':{
		'title':'订单详细',
		'personnel':'人员',
		'operator':'操作',
		'seller':'销售',
		'Box':'箱型箱量',
		'freight':'运费',
		'Charges':'附加费',
		'information':'运单信息',
		'Other':'其他信息',
		'transport':'运输方式',
		'field1':'起运港',
		'field2':'目的港',
		'field3':'船公司',
		'field4':'中转港',
		'field5':'船程',
		'field6':'开船',
		'field7':'截关',
		'field8':'截止日期',
		'field9':'箱型箱量',
		'field10':'预计出货时间',
		'field11':'选择时间',
		'field12':'备注',
		'field13':'询价',
		'field14':'船期信息',
		'field21':'查看物流状态',
		'field18':'成本',
		'field19':'报价',
		'field20':'利润',
		'cost':'成本',
		'offer':'报价',
		
	}
}

var arrHyfCurrency=['(单位：人民币)','(单位：美元)','(单位：泰铢)'];
var arrTransportation=['CY-CY','CY-DOOR','DOOR-DOOR'];
var arrCurrency=['￥','$','฿'];