var languageName=['CN','US'];
var langText={
	'US':{
		'title':'The current order',
		'field1':'Order number：',
		'field2':'Order time：',
		'field3':'Ship name：',
		'field4':'Voyage：',
		'field5':'Range：',
		'field6':'Departure time：',
		'field7':'Box Quantity：',
		'field8':'Carry：',
		'field9':'Quotation Status',
		'field10':'not offer',
		'field11':'has offer',
		'field12':'POL',
		'field13':'POD',
		'field14':'POT',
		'field15':'Customer：',
		'field16':'Contact details：',
		'field17':'Linkman：',
		'field18':'Consigner：',
		'field19':'Consignee：',
		'field20':'Notifier：',
		'field21':'MBL：',
		'extract':'ExtractBox',
		'truck':'TruckGPS',
		'enter':'EnterPort',
		'manifest':'Manifest',
		'inspection':'CustomsInspection',
		'release':'CustomsRelease',
		'clearance':'PortClearance',
		'loading':'Loading',
		'lading':'Lading',
		'sail':'Sail',
		'journey':'Journey',
		'CarryWebsite':'CarryWebsite',
		'arrive':'Arrive',
	},
	'CN':{
		'title':'当前订单',
		'field1':'订单编号：',
		'field2':'下单时间：',
		'field3':'船名：',
		'field4':'航次：',
		'field5':'船程：',
		'field6':'开船时间：',
		'field7':'箱型箱量：',
		'field8':'船公司：',
		'field9':'报价状态',
		'field10':'未报价',
		'field11':'已报价',
		'field12':'起运港',
		'field13':'目的港',
		'field14':'中转港：',
		'field15':'客户：',
		'field16':'联系方式：',
		'field17':'联系人：',
		'field18':'发货人：',
		'field19':'收货人：',
		'field20':'通知人：',
		'field21':'提单号：',
		'extract':'提空箱',
		'truck':'集卡GPS',
		'enter':'重箱进港',
		'manifest':'预配舱单',
		'inspection':'海关查验',
		'release':'海关放行',
		'clearance':'码头放行',
		'loading':'装载仓单',
		'lading':'重箱装船',
		'sail':'开船',
		'journey':'船舶在途',
		'CarryWebsite':'船公司网站查询',
		'arrive':'到达目的地',
	}
}